stages:
  - scanner
  - build

scanner:
  stage : scanner
  only:
    - master
  tags:
    - coachrun-pc
  script:
    - /usr/local/sonar-scanner/bin/sonar-scanner


#测试环境构建job
build:
  stage: build
  only:
    - master
  tags:
    - coachrun-pc
  script:
    - npm --registry https://registry.npm.taobao.org install express
    - rm -rf node_modules package-lock.json && npm install
    - npm run build

