stages:
 - sandbox
 - build

#打包部署
sandbox:
 stage: sandbox
 only:
   - test         #指定分支，只允许master
 tags:
   - coachrun-pc
 script:
    - npm --registry https://registry.npm.taobao.org install express
    - rm -rf node_modules package-lock.json && npm install
    - npm run build
    - scp -r vue root@192.168.20.9:/var/www/vhosts/test-servers/coachrun.com/www
    - echo success
    
build:
  stage: build
  tags:
   - pc
  only:
   - master
  script:
   - npm --registry https://registry.npm.taobao.org install express
   - rm -rf node_modules package-lock.json && npm install
   - npm run build
