stages:
 - deploy
#打包部署
deploy:
 stage: deploy
 environment:
   name: coachrun-pc
   url: http://coachrun.com
 only:
   - test         #指定分支，只允许master
 tags:
   - coachrun-pc
 script:
    - npm --registry https://registry.npm.taobao.org install express
    - rm -rf node_modules package-lock.json && npm install
    - npm run sandbox
    - scp -r vue root@192.168.20.9:/var/www/vhosts/test-servers/coachrun.com/www/
    - echo success

