cache:
  paths:
  - node_modules/

stages:
  - sandbox
  - live

sandbox:
  stage: sandbox
  only:
    - dev
  tags:
    - coachrun-pc
  script:
    - npm install --no-optional --no-shrinkwrap --no-package-lock
    - npm run sandbox
    - scp -r vue root@192.168.20.9:/var/www/vhosts/test-servers/coachrun.com/www

live:
  stage: live
  only:
    - master
  tags:
    - pc
  script:
    - npm install --no-optional --no-shrinkwrap --no-package-lock
    - npm run build
    - /home/gitlab-runner/coachrun-desktop.sh