stages:
 - deploy
#打包部署
deploy:
 stage: deploy
 environment:
   name: pc
   url: http://coachrun.com
 only:
   - master         #指定分支，只允许master
 tags:
   - pc
 script:
    - npm --registry https://registry.npm.taobao.org install express
    - rm -rf node_modules package-lock.json && npm install
    - npm run build
    - echo success